# In this notebook, we're going to cover some of the most fundamental concepts of tensorflow

We're going to cover

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function( a way to speed up python functions)
* Using GPUS with tensorflow or TPUS
* Exercises to try


# Introduction to Tensorflow

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim = number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix(matrix has more than 1 dimensions)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix(matrix has more than 1 dimensions)
another_matrix = tf.constant([[10.,7.],[7.,10.],[8.,9.]],dtype=tf.float16) # Create a matrix of 3 dimensions with values of float16
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Tensor
tensor = tf.constant([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## What we've created so far

* Scalar is single number
* Vector is a number with direction
* Matrix is a 2 dimensional array of numbers
* Tensor is an n-dimensional array of numbers where n can be any number

### Creating tf variable

In [ ]:
# Create same tensor using variable as we had previously
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#changeable_tensor[0] = 7

In [ ]:
# using assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# lets try changing unchangeable
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some arbitrary size filled with random numbers

In [ ]:
### Let's create 2 random tensors of 2 sizes
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
print(random_1)
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
print(random_2)
random_1 == random_2

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-1.3240396   0.28785667]
 [-0.8757901  -0.08857018]
 [ 0.69211644  0.84215707]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### shuffle order of elements in tensor

In [ ]:
### shuffle order of elements in tensor good for model training
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle not shuffled tensor
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled,seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

***Exercise*** read through tensorflow documentation on random seed generation

Important note would need to set global and operator seed to get same result everytime to allow reproduction

In [ ]:
# create tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensors of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### turn numpy arrays into tensors
Difference between numpy arrays and tensorflow tensors is that tensors can be run on a gpu

In [ ]:
### turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32) # Creates numpy array between 1 and 25

# X = tf.constant(some_matrix)
# Y = tf.constant[vector]
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape=(2,3,4))
B= tf.constant(numpy_A)
A,B
#A.ndim
#B.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you probably want to be aware of following attributes

+ Shape
+ Rank
+ Axis or dimension
+ Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions(rank): ", rank_4_tensor.ndim)
print("shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions(rank):  4
shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in the tensor:  120


### indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
# get the first 2 elements of each of our tensors
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element of each of our tensors except for final tensor
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.zeros(shape=[2,2])
rank_2_tensor
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get last item of each row of rank 2 tensor
rank_2_tensor[:,:-1]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [ ]:
# Adding extra dimension to our tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
#Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

### Manipulating tensors(tensor operations)

***Basic Operations ***

+,-, *, /

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor += 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor -= 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor *=10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor /=10

**Matrix multiplication**

In machine learning matrix multiplications are one of the most common operations performed on tensors

There are two rules or tensors need to fulfil if we're going to mutiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of inner dimensions



In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10.  7.]
 [ 3.  4.]], shape=(2, 2), dtype=float64)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[121.,  98.],
       [ 42.,  37.]])>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[100.,  49.],
       [  9.,  16.]])>

In [ ]:
# matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[121.,  98.],
       [ 42.,  37.]])>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [58]:
# Create a tensor of 2 * 3
X = tf.constant([[1,2,3],[4,5,6]])
# Another 3 * 2 tensor
Y = tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
  # Multiply tensors of same shape
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [67]:
# reshape tensor
X = tf.constant([[1,2],[3,4],[5,6]])
reshaped_y = tf.reshape(Y,shape=(2,3))


In [71]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [70]:
reshaped_y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [68]:
X @ reshaped_y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

**Resource** info and example of resource multiplication https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [72]:
tf.matmul(X,reshaped_y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [75]:
#Can do same with transpose
X, tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [77]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also known as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot`