<a href="https://colab.research.google.com/github/Ultan-Kearns/ZTM-Tensorflow-Developer-Certificate/blob/master/Exercise_1_Used_car_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1246]:
# import libraries
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd

tf.random.set_seed(42)
# Find suitable dataset
used_cars_df = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/usedcars.csv")

In [1247]:
used_cars_df

year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [1248]:
X = used_cars_df.drop("price",axis=1)
y = used_cars_df.price

In [1249]:
X

year model  mileage   color transmission
0    2011   SEL     7413  Yellow         AUTO
1    2011   SEL    10926    Gray         AUTO
2    2011   SEL     7351  Silver         AUTO
3    2011   SEL    11613    Gray         AUTO
4    2012    SE     8367   White         AUTO
..    ...   ...      ...     ...          ...
145  2006   SES    95000  Silver         AUTO
146  2002    SE    87003     Red         AUTO
147  2000    SE    96841     Red         AUTO
148  2001    SE   151479  Yellow         AUTO
149  2000    SE   109259     Red         AUTO

[150 rows x 5 columns]

In [1250]:
y

0      21992
1      20995
2      19995
3      17809
4      17500
       ...  
145     6200
146     5995
147     5980
148     4899
149     3800
Name: price, Length: 150, dtype: int64

In [1251]:

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)

# for missing columns
# Assuming X_train and X_test have the same columns
common_columns = X_train.columns

# Reorder columns in X_test to match the order in X_train
X_test = X_test[common_columns]


In [1252]:
X_test

year model  mileage   color transmission
73   2009   SEL    27528  Silver         AUTO
18   2011   SEL    11662    Blue         AUTO
118  2007   SES    77231     Red         AUTO
78   2010    SE    34503   Black         AUTO
76   2009   SES    64055   Black         AUTO
31   2009    SE    34419   Black       MANUAL
64   2009    SE     9450   Black         AUTO
141  2007    SE    86862   White         AUTO
68   2009    SE    50533   White         AUTO
82   2007    SE    39665     Red         AUTO
110  2008    SE    85229     Red       MANUAL
12   2011   SEL     9388   Green         AUTO
36   2011    SE    23967   White         AUTO
9    2010   SES    36116  Silver         AUTO
19   2011   SEL    32069  Silver         AUTO

In [1253]:
y_train

56     13995
104    11984
69     13845
55     13995
132     8495
       ...  
71     13742
106    11792
14     16000
92     12988
102    11999
Name: price, Length: 135, dtype: int64

In [1254]:
y_test

73     13663
18     15992
118    10815
78     13383
76     13425
31     14995
64     13950
141     6995
68     13888
82     12997
110    11450
12     16950
36     14989
9      16995
19     15992
Name: price, dtype: int64

In [1255]:
x_model_dummies = pd.get_dummies(X_train.model)
x_color_dummmies = pd.get_dummies(X_train.color)
x_transmission_dummies = pd.get_dummies(X_train.transmission)

In [1256]:
X_train = pd.concat([X_train,x_model_dummies],axis=1)
X_train = X_train.drop("model",axis=1)

In [1257]:
X_train = pd.concat([X_train,x_color_dummmies],axis=1)
X_train = X_train.drop("color",axis=1)

In [1258]:
X_train = pd.concat([X_train,x_transmission_dummies],axis=1)
X_train = X_train.drop("transmission",axis=1)

In [1259]:
X_train

year  mileage  SE  SEL  SES  Black  Blue  Gold  Gray  Green  Red  Silver  \
56   2010    20278   1    0    0      1     0     0     0      0    0       0   
104  2009    59048   0    0    1      1     0     0     0      0    0       0   
69   2009    36713   1    0    0      0     1     0     0      0    0       0   
55   2010    13541   1    0    0      0     0     0     0      0    0       1   
132  2008   106171   1    0    0      1     0     0     0      0    0       0   
..    ...      ...  ..  ...  ...    ...   ...   ...   ...    ...  ...     ...   
71   2009    38380   0    0    1      1     0     0     0      0    0       0   
106  2010    39722   1    0    0      0     0     0     0      1    0       0   
14   2011    15367   1    0    0      0     0     0     0      0    0       0   
92   2009    31538   1    0    0      0     0     0     1      0    0       0   
102  2009    36124   1    0    0      0     1     0     0      0    0       0   

     White  Yellow  AUTO  MANUAL  
56       0       0     0       1  
104      0       0     1       0  
69       0       0     1       0  
55       0       0     1       0  
132      0       0     1       0  
..     ...     ...   ...     ...  
71       0       0     1       0  
106      0       0     1       0  
14       1       0     1       0  
92       0       0     1       0  
102      0       0     1       0  

[135 rows x 16 columns]

In [1260]:
x_model_dummies = pd.get_dummies(X_test.model)
x_color_dummmies = pd.get_dummies(X_test.color)
x_transmission_dummies = pd.get_dummies(X_test.transmission)

In [1261]:
X_test = pd.concat([X_test,x_model_dummies],axis=1)
X_test = X_test.drop("model",axis=1)

In [1262]:
X_test = pd.concat([X_test,x_color_dummmies],axis=1)
X_test = X_test.drop("color",axis=1)

In [1263]:
X_test = pd.concat([X_test,x_transmission_dummies],axis=1)
X_test = X_test.drop("transmission",axis=1)

In [1264]:
X_test

year  mileage  SE  SEL  SES  Black  Blue  Green  Red  Silver  White  \
73   2009    27528   0    1    0      0     0      0    0       1      0   
18   2011    11662   0    1    0      0     1      0    0       0      0   
118  2007    77231   0    0    1      0     0      0    1       0      0   
78   2010    34503   1    0    0      1     0      0    0       0      0   
76   2009    64055   0    0    1      1     0      0    0       0      0   
31   2009    34419   1    0    0      1     0      0    0       0      0   
64   2009     9450   1    0    0      1     0      0    0       0      0   
141  2007    86862   1    0    0      0     0      0    0       0      1   
68   2009    50533   1    0    0      0     0      0    0       0      1   
82   2007    39665   1    0    0      0     0      0    1       0      0   
110  2008    85229   1    0    0      0     0      0    1       0      0   
12   2011     9388   0    1    0      0     0      1    0       0      0   
36   2011    23967   1    0    0      0     0      0    0       0      1   
9    2010    36116   0    0    1      0     0      0    0       1      0   
19   2011    32069   0    1    0      0     0      0    0       1      0   

     AUTO  MANUAL  
73      1       0  
18      1       0  
118     1       0  
78      1       0  
76      1       0  
31      0       1  
64      1       0  
141     1       0  
68      1       0  
82      1       0  
110     0       1  
12      1       0  
36      1       0  
9       1       0  
19      1       0

In [1265]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1),
    tf.keras.layers.Dense(10,activation="relu"),
    tf.keras.layers.Dense(1),
    ])
model.compile(loss=tf.keras.losses.mae,optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),metrics=["mae"])
model.fit(X_train,y_train,epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 4ms/step - loss: 12219.8369 - mae: 12219.8369
Epoch 2/200
5/5 [==============================] - 0s 3ms/step - loss: 10033.9463 - mae: 10033.9463
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 7697.5425 - mae: 7697.5425
Epoch 4/200
5/5 [==============================] - 0s 3ms/step - loss: 7188.5708 - mae: 7188.5708
Epoch 5/200
5/5 [==============================] - 0s 3ms/step - loss: 7703.5547 - mae: 7703.5547
Epoch 6/200
5/5 [==============================] - 0s 4ms/step - loss: 7412.4077 - mae: 7412.4077
Epoch 7/200
5/5 [==============================] - 0s 3ms/step - loss: 7054.1104 - mae: 7054.1104
Epoch 8/200
5/5 [==============================] - 0s 4ms/step - loss: 6851.3525 - mae: 6851.3525
Epoch 9/200
5/5 [==============================] - 0s 5ms/step - loss: 6801.2798 - mae: 6801.2798
Epoch 10/200
5/5 [==============================] - 0s 4ms/step - loss: 6686.9990 - mae: 6686.9990
Epoch 11/200
5/

In [1266]:
X_test

year  mileage  SE  SEL  SES  Black  Blue  Green  Red  Silver  White  \
73   2009    27528   0    1    0      0     0      0    0       1      0   
18   2011    11662   0    1    0      0     1      0    0       0      0   
118  2007    77231   0    0    1      0     0      0    1       0      0   
78   2010    34503   1    0    0      1     0      0    0       0      0   
76   2009    64055   0    0    1      1     0      0    0       0      0   
31   2009    34419   1    0    0      1     0      0    0       0      0   
64   2009     9450   1    0    0      1     0      0    0       0      0   
141  2007    86862   1    0    0      0     0      0    0       0      1   
68   2009    50533   1    0    0      0     0      0    0       0      1   
82   2007    39665   1    0    0      0     0      0    1       0      0   
110  2008    85229   1    0    0      0     0      0    1       0      0   
12   2011     9388   0    1    0      0     0      1    0       0      0   
36   2011    23967   1    0    0      0     0      0    0       0      1   
9    2010    36116   0    0    1      0     0      0    0       1      0   
19   2011    32069   0    1    0      0     0      0    0       1      0   

     AUTO  MANUAL  
73      1       0  
18      1       0  
118     1       0  
78      1       0  
76      1       0  
31      0       1  
64      1       0  
141     1       0  
68      1       0  
82      1       0  
110     0       1  
12      1       0  
36      1       0  
9       1       0  
19      1       0

In [1267]:
X_train

year  mileage  SE  SEL  SES  Black  Blue  Gold  Gray  Green  Red  Silver  \
56   2010    20278   1    0    0      1     0     0     0      0    0       0   
104  2009    59048   0    0    1      1     0     0     0      0    0       0   
69   2009    36713   1    0    0      0     1     0     0      0    0       0   
55   2010    13541   1    0    0      0     0     0     0      0    0       1   
132  2008   106171   1    0    0      1     0     0     0      0    0       0   
..    ...      ...  ..  ...  ...    ...   ...   ...   ...    ...  ...     ...   
71   2009    38380   0    0    1      1     0     0     0      0    0       0   
106  2010    39722   1    0    0      0     0     0     0      1    0       0   
14   2011    15367   1    0    0      0     0     0     0      0    0       0   
92   2009    31538   1    0    0      0     0     0     1      0    0       0   
102  2009    36124   1    0    0      0     1     0     0      0    0       0   

     White  Yellow  AUTO  MANUAL  
56       0       0     0       1  
104      0       0     1       0  
69       0       0     1       0  
55       0       0     1       0  
132      0       0     1       0  
..     ...     ...   ...     ...  
71       0       0     1       0  
106      0       0     1       0  
14       1       0     1       0  
92       0       0     1       0  
102      0       0     1       0  

[135 rows x 16 columns]

In [1268]:
X_test

year  mileage  SE  SEL  SES  Black  Blue  Green  Red  Silver  White  \
73   2009    27528   0    1    0      0     0      0    0       1      0   
18   2011    11662   0    1    0      0     1      0    0       0      0   
118  2007    77231   0    0    1      0     0      0    1       0      0   
78   2010    34503   1    0    0      1     0      0    0       0      0   
76   2009    64055   0    0    1      1     0      0    0       0      0   
31   2009    34419   1    0    0      1     0      0    0       0      0   
64   2009     9450   1    0    0      1     0      0    0       0      0   
141  2007    86862   1    0    0      0     0      0    0       0      1   
68   2009    50533   1    0    0      0     0      0    0       0      1   
82   2007    39665   1    0    0      0     0      0    1       0      0   
110  2008    85229   1    0    0      0     0      0    1       0      0   
12   2011     9388   0    1    0      0     0      1    0       0      0   
36   2011    23967   1    0    0      0     0      0    0       0      1   
9    2010    36116   0    0    1      0     0      0    0       1      0   
19   2011    32069   0    1    0      0     0      0    0       1      0   

     AUTO  MANUAL  
73      1       0  
18      1       0  
118     1       0  
78      1       0  
76      1       0  
31      0       1  
64      1       0  
141     1       0  
68      1       0  
82      1       0  
110     0       1  
12      1       0  
36      1       0  
9       1       0  
19      1       0

In [1269]:
# code courtesy of chatgpt
def add_missing_columns(df1, df2):
    missing_columns = set(df2.columns) - set(df1.columns)
    for col in missing_columns:
        df1[col] = 0  # You can change 'None' to any default value you want
add_missing_columns(X_test,X_train)

In [1270]:
X_test

year  mileage  SE  SEL  SES  Black  Blue  Green  Red  Silver  White  \
73   2009    27528   0    1    0      0     0      0    0       1      0   
18   2011    11662   0    1    0      0     1      0    0       0      0   
118  2007    77231   0    0    1      0     0      0    1       0      0   
78   2010    34503   1    0    0      1     0      0    0       0      0   
76   2009    64055   0    0    1      1     0      0    0       0      0   
31   2009    34419   1    0    0      1     0      0    0       0      0   
64   2009     9450   1    0    0      1     0      0    0       0      0   
141  2007    86862   1    0    0      0     0      0    0       0      1   
68   2009    50533   1    0    0      0     0      0    0       0      1   
82   2007    39665   1    0    0      0     0      0    1       0      0   
110  2008    85229   1    0    0      0     0      0    1       0      0   
12   2011     9388   0    1    0      0     0      1    0       0      0   
36   2011    23967   1    0    0      0     0      0    0       0      1   
9    2010    36116   0    0    1      0     0      0    0       1      0   
19   2011    32069   0    1    0      0     0      0    0       1      0   

     AUTO  MANUAL  Gold  Yellow  Gray  
73      1       0     0       0     0  
18      1       0     0       0     0  
118     1       0     0       0     0  
78      1       0     0       0     0  
76      1       0     0       0     0  
31      0       1     0       0     0  
64      1       0     0       0     0  
141     1       0     0       0     0  
68      1       0     0       0     0  
82      1       0     0       0     0  
110     0       1     0       0     0  
12      1       0     0       0     0  
36      1       0     0       0     0  
9       1       0     0       0     0  
19      1       0     0       0     0

from matplotlib import pyplot as plt
X_test['year'].plot(kind='hist', bins=20, title='year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test['mileage'].plot(kind='hist', bins=20, title='mileage')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test['SE'].plot(kind='hist', bins=20, title='SE')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test['SEL'].plot(kind='hist', bins=20, title='SEL')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test.plot(kind='scatter', x='year', y='mileage', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test.plot(kind='scatter', x='mileage', y='SE', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test.plot(kind='scatter', x='SE', y='SEL', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_test.plot(kind='scatter', x='SEL', y='SES', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['mileage']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = X_test.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('mileage')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['SE']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = X_test.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('SE')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['SEL']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = X_test.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('SEL')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['SES']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = X_test.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('SES')

from matplotlib import pyplot as plt
X_test['year'].plot(kind='line', figsize=(8, 4), title='year')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_test['mileage'].plot(kind='line', figsize=(8, 4), title='mileage')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_test['SE'].plot(kind='line', figsize=(8, 4), title='SE')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_test['SEL'].plot(kind='line', figsize=(8, 4), title='SEL')
plt.gca().spines[['top', 'right']].set_visible(False)

In [1271]:
y_pred = model.predict(X_test)

1/1 [==============================] - 0s 66ms/step


In [1272]:
y_pred[5]

array([13770.034], dtype=float32)

In [1273]:
y_test.values[5]

14995

In [1274]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 142ms/step - loss: 1379.9458 - mae: 1379.9458


[1379.94580078125, 1379.94580078125]

## Testing normalization

In [1275]:
y_train_max_values = tf.math.reduce_max(y_train, axis=0, keepdims=True)
y_train_norm = y_train / tf.cast(y_train_max_values, y_test.dtype)


In [1276]:
y_train_max_values

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([21992])>

In [1277]:
y_test_max_values = tf.math.reduce_max(y_test, axis=0, keepdims=True)
y_test_norm = y_test / tf.cast(y_test_max_values, y_test.dtype)

In [1278]:
y_test_max_values

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([16995])>

In [1279]:
y_test_norm

73     0.803942
18     0.940983
118    0.636364
78     0.787467
76     0.789938
31     0.882318
64     0.820830
141    0.411592
68     0.817182
82     0.764754
110    0.673728
12     0.997352
36     0.881965
9      1.000000
19     0.940983
Name: price, dtype: float64

In [1310]:
norm_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1),
    tf.keras.layers.Dense(12,activation="relu"),
    tf.keras.layers.Dense(1),
    ])
norm_model.compile(loss=tf.keras.losses.mae,optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),metrics=["mae"])
norm_model.fit(X_train,y_train_norm,epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 4ms/step - loss: 3168.3972 - mae: 3168.3972
Epoch 2/200
5/5 [==============================] - 0s 6ms/step - loss: 1386.3409 - mae: 1386.3409
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 236.9989 - mae: 236.9989
Epoch 4/200
5/5 [==============================] - 0s 3ms/step - loss: 333.9862 - mae: 333.9862
Epoch 5/200
5/5 [==============================] - 0s 3ms/step - loss: 310.9395 - mae: 310.9395
Epoch 6/200
5/5 [==============================] - 0s 3ms/step - loss: 133.4521 - mae: 133.4521
Epoch 7/200
5/5 [==============================] - 0s 4ms/step - loss: 32.5729 - mae: 32.5729
Epoch 8/200
5/5 [==============================] - 0s 3ms/step - loss: 68.9544 - mae: 68.9544
Epoch 9/200
5/5 [==============================] - 0s 4ms/step - loss: 41.6044 - mae: 41.6044
Epoch 10/200
5/5 [==============================] - 0s 3ms/step - loss: 7.1498 - mae: 7.1498
Epoch 11/200
5/5 [===========================

In [1311]:
norm_model.evaluate(X_test,y_test_norm)

1/1 [==============================] - 0s 123ms/step - loss: 0.1699 - mae: 0.1699


[0.1698714941740036, 0.1698714941740036]

In [1312]:
y_test_norm[:10] * 16995

73     13663.0
18     15992.0
118    10815.0
78     13383.0
76     13425.0
31     14995.0
64     13950.0
141     6995.0
68     13888.0
82     12997.0
Name: price, dtype: float64

In [1313]:
norm_model.predict(X_test[:10]) * 16995

1/1 [==============================] - 0s 57ms/step


array([[11887.4795],
       [12859.179 ],
       [ 8923.935 ],
       [11469.839 ],
       [ 9690.526 ],
       [11467.182 ],
       [12992.487 ],
       [ 8280.295 ],
       [10483.86  ],
       [11191.1   ]], dtype=float32)

In [1284]:
y_test[:10]

73     13663
18     15992
118    10815
78     13383
76     13425
31     14995
64     13950
141     6995
68     13888
82     12997
Name: price, dtype: int64

In [1285]:
model.predict(X_test[:10])

1/1 [==============================] - 0s 38ms/step


array([[14477.032],
       [16039.014],
       [ 9707.995],
       [13789.61 ],
       [10980.354],
       [13770.034],
       [16182.32 ],
       [ 8731.842],
       [12230.781],
       [13276.859]], dtype=float32)

In [1286]:
y_test

73     13663
18     15992
118    10815
78     13383
76     13425
31     14995
64     13950
141     6995
68     13888
82     12997
110    11450
12     16950
36     14989
9      16995
19     15992
Name: price, dtype: int64

In [1287]:
y_test_norm * 16995

73     13663.0
18     15992.0
118    10815.0
78     13383.0
76     13425.0
31     14995.0
64     13950.0
141     6995.0
68     13888.0
82     12997.0
110    11450.0
12     16950.0
36     14989.0
9      16995.0
19     15992.0
Name: price, dtype: float64